-- DDL 수정: RCVPAY_DT 컬럼 타입 수정
-- 문제: VARCHAR(100) DEFAULT CURRENT_TIMESTAMP (불가능한 조합)
-- 해결: DATETIME DEFAULT CURRENT_TIMESTAMP로 변경

-- 1. RCVPAY_DT 컬럼 타입 수정
ALTER TABLE WRHOUS_WRHSDLVR_MAS 
MODIFY COLUMN RCVPAY_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 2. 기존 VARCHAR 날짜 데이터를 DATETIME으로 변환이 필요한 경우 실행
-- (만약 기존에 '2025-10-16' 형태의 문자열 데이터가 있다면)
-- UPDATE WRHOUS_WRHSDLVR_MAS 
-- SET RCVPAY_DT = STR_TO_DATE(RCVPAY_DT, '%Y-%m-%d')
-- WHERE RCVPAY_DT REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$';

-- 3. 변경 결과 확인
DESCRIBE WRHOUS_WRHSDLVR_MAS;