CREATE TABLE PROD_DRCT (
	`PROD_DRCT_ID`	VARCHAR(100)	NOT NULL,
	`PROD_DRCT_NM`	VARCHAR(1000)	NOT NULL,
	`EMP_ID`	VARCHAR(100)	NOT NULL,
	`PROD_DRCT_FR_DT`	DATE	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`PROD_DRCT_TO_DT`	DATE	NULL,
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE PROD_PLAN (
	`PROD_PLAN_ID`	VARCHAR(100)	NOT NULL,
	`RCVODR_ID`	VARCHAR(100)	NOT NULL	COMMENT '수주 식별자',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`PROD_PLAN_NM`	VARCHAR(100)	NOT NULL,
	`PROD_EXPC_FR_DT`	DATE	NOT NULL,
	`PROD_EXPC_TO_DT`	DATE	NULL,
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE DELI_REG_DETA (
	`DELI_DOC_REG_DETA_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_DELI_DOC_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_RCVORD_DETA_ID`	VARCHAR(100)	NOT NULL	COMMENT '수주 상세 테이블 식별자',
	`DELI_QY`	INT	NOT NULL,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE WRHOUS (
	`WRHOUS_ID`	VARCHAR(100)	NOT NULL	COMMENT '창고 식별자',
	`WRHOUS_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)자재 창고',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT '활성화 구분 코드 참조',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE MENU_PERM (
	`MENU_PERM_ID`	VARCHAR(100)	NOT NULL,
	`MENU_ID`	VARCHAR(100)	NOT NULL,
	`DEPT_ID`	VARCHAR(100)	NOT NULL	COMMENT '공통 코드 참조',
	`WKGD_ID`	VARCHAR(100)	NOT NULL	COMMENT '공통 코드 참조',
	`ACCES_YN`	VARCHAR(100)	NOT NULL	COMMENT 'Y/N 공통 코드 참조',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE ACCT (
	`ACCT_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`ID`	VARCHAR(100)	NOT NULL	COMMENT 'ex)타락파워전사',
	`PW`	VARCHAR(100)	NOT NULL	COMMENT 'ex)1234@',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE PROD_DRCT_DETA (
	`PROD_DRCT_DETA_ID`	VARCHAR(255)	NOT NULL,
	`PROD_DRCT_ID`	VARCHAR(100)	NOT NULL,
	`PROD_PLAN_DETA_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_OPT_ID`	VARCHAR(100)	NOT NULL,
	`DRCT_QY`	INT	NOT NULL,
	`PRIORT`	INT	NOT NULL,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE LOT_STC_PRECON (
	`LOT_INVNTRY_PRECON_ID`	VARCHAR(100)	NOT NULL,
	`WRHOUS_WRHSDLVR_ID`	VARCHAR(100)	NOT NULL,
	`IST_QY`	INT	NULL,
	`OUST_QY`	INT	NULL,
	`NOW_STC_QY`	INT	NOT NULL	COMMENT '현재 수량',
	`RM`	VARCHAR(1000)	NULL	COMMENT '재고 특이사항'
);

CREATE TABLE EQM_GRP (
	`EQM_GRP_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`EQM_GRP_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)프레스/사출',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE RSC (
	`RSC_ID`	VARCHAR(100)	NOT NULL	COMMENT '자재 식별자',
	`RSC_CLSF_ID`	VARCHAR(100)	NOT NULL	COMMENT '부코드 ID 입력',
	`RSC_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)텅스텐파우더',
	`SPEC`	VARCHAR(100)	NOT NULL	COMMENT 'ex)입자크기',
	`UNIT`	VARCHAR(100)	NOT NULL	COMMENT 'ex)kg, L, EA',
	`RM`	VARCHAR(1000)	NULL	COMMENT '자재 특이사항'
);

CREATE TABLE MOLD (
	`MOLD_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품 테이블 FK',
	`MOLD_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)금형회사이름_1',
	`MOLD_TY`	VARCHAR(100)	NOT NULL	COMMENT 'ex)프레스/사출',
	`KPA`	INT	NOT NULL	COMMENT '24시간 한달기준 얼마나 제품을 찍어내는가에 대한 수치',
	`ACCMLT_SHOT`	INT	NULL	COMMENT 'ex)2,000',
	`WARN_QY`	INT	NOT NULL,
	`DSUSE_QY`	INT	NOT NULL	COMMENT 'ex)10,000',
	`CHCK_CYCLE`	VARCHAR(100)	NOT NULL	COMMENT 'ex)1일/7일/30일',
	`CHCK_DT`	DATE	NULL	COMMENT '마지막 점검 일자',
	`ST`	VARCHAR(100)	NULL	COMMENT '사용 중, 사용 불가능, 사용 가능',
	`RM`	VARCHAR(100)	NULL
);

CREATE TABLE PRDT (
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품과 규격에 따라 ID를 구분한다.',
	`PRDT_NM`	VARCHAR(100)	NOT NULL	COMMENT '제품 이름',
	`SPEC`	VARCHAR(100)	NOT NULL	COMMENT 'ex) 20g',
	`UNIT`	VARCHAR(100)	NOT NULL	COMMENT '공통코드 단위에서 값을 가져온다',
	`PRDT_ST`	VARCHAR(100)	NOT NULL	COMMENT '사용 구분 코드',
	`RM`	VARCHAR(1000)	NULL	COMMENT '제품의 특이사항'
);

CREATE TABLE RCVORD_DETA (
	`PRDT_RCVORD_DETA_ID`	VARCHAR(100)	NOT NULL	COMMENT '수주 상세 테이블 식별자',
	`RCVODR_ID`	VARCHAR(100)	NOT NULL	COMMENT '수주 식별자',
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품 테이블 FK',
	`PRDT_OPT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품 옵션 테이블 FK',
	`RCVORD_QY`	INT	NOT NULL	COMMENT '수주 받은 제품의 수량',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT 'ex)진행중',
	`PAPRD_DT`	DATE	NOT NULL	COMMENT 'ex)2025-11-30',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE MA_CODE (
	`MA_CODE_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`MA_CODE_NM`	VARCHAR(100)	NOT NULL	COMMENT '부서/메뉴/직급/권한/여부/품목/단위/규격/업체유형/자재분류/유무/활성비활성/사용미사용/가동비가동/진행중취소완료/합격불합격'
);

CREATE TABLE BOM_DETA (
	`BOM_COMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`BOM_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`RSC_ID`	VARCHAR(100)	NOT NULL	COMMENT '자재 테이블 FK',
	`SPEC_ID`	VARCHAR(100)	NULL	COMMENT 'ex) g, ml',
	`UNIT_ID`	VARCHAR(100)	NOT NULL	COMMENT '부코드 ID 입력',
	`REC_QY`	FLOAT(15,5)	NOT NULL	COMMENT 'ex)0.032',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE EQM (
	`EQM_ID`	VARCHAR(100)	NOT NULL	COMMENT '설비명',
	`EQM_GRP_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`EQM_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)프레스기_1',
	`MAKE_CO`	VARCHAR(100)	NULL	COMMENT 'ex)프레스월드',
	`MAKE_MODEL`	VARCHAR(100)	NULL	COMMENT 'ex)ABC_123',
	`MAKE_DT`	DATE	NULL	COMMENT 'ex)2020-01-01',
	`CHCK_CYCLE`	VARCHAR(100)	NOT NULL	COMMENT 'ex)1일/7일/30일',
	`SETP_DT`	DATE	NULL	COMMENT 'ex)2025-09-09',
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ex)2025-09-30',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT '공통 코드 가동/비가동 참조',
	`RM`	VARCHAR(2000)	NULL
);

CREATE TABLE QLTY_ITEM (
	`QLTY_ITEM_MNG_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`INSP_ITEM_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)외관 검사',
	`TY`	VARCHAR(100)	NOT NULL	COMMENT 'ex)정량',
	`VER`	VARCHAR(100)	NOT NULL	COMMENT 'ex)v1',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT '사용/미사용',
	`BASI_VAL`	VARCHAR(100)	NULL	COMMENT 'ex)10cm',
	`SPEC`	VARCHAR(100)	NOT NULL	COMMENT 'ex)-',
	`UNIT`	VARCHAR(100)	NOT NULL	COMMENT 'ex)EA',
	`EROR_SCOPE_MIN`	VARCHAR(100)	NULL,
	`EROR_SCOPE_MAX`	VARCHAR(100)	NULL	COMMENT 'ex)2cm',
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT 'ex)2025-09-09',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE EMP (
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`CO_ID`	VARCHAR(100)	NOT NULL	COMMENT '업체 테이블 FK',
	`DEPT_ID`	VARCHAR(100)	NULL	COMMENT '부코드 ID 입력',
	`PERM_ID`	VARCHAR(100)	NOT NULL	COMMENT '부코드 ID 입력 메뉴 구분 코드',
	`WKGD_ID`	VARCHAR(100)	NOT NULL	COMMENT '부코드 ID 입력',
	`EMP_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)홍길동',
	`EMP_TEL`	VARCHAR(100)	NOT NULL	COMMENT 'ex)010-1234-1234',
	`EMP_EMAIL`	VARCHAR(100)	NOT NULL	COMMENT 'ex)email@naver.com',
	`HIRE_DT`	DATE	NOT NULL	COMMENT 'ex)2025-09-09',
	`HOOF_ST`	VARCHAR(100)	NOT NULL	COMMENT '재직 구분 코드',
	`RM`	VARCHAR(1000)	NULL	COMMENT 'ex)폐급/에이스'
);

CREATE TABLE RCVORD (
	`RCVODR_ID`	VARCHAR(100)	NOT NULL	COMMENT '수주 식별자',
	`CO_ID`	VARCHAR(100)	NOT NULL	COMMENT '업체 테이블 FK',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원테이블 FK(담당자))',
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일자',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE RWMATR_RTUN_TRGET (
	`RSC_RTUN_TRGET_ID`	VARCHAR(100)	NOT NULL,
	`PROD_DRCT_ITEM_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_OPT_ID`	VARCHAR(100)	NOT NULL,
	`PROD_EXPC_QY`	INT	NOT NULL,
	`PROD_EXPC_DT`	DATE	NOT NULL,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE ITEM_QLTY_DETA (
	`ITEM_QLTY_DETA_ID`	VARCHAR(255)	NOT NULL	COMMENT '품질 항목 별 품목 매핑',
	`QLTY_ITEM_MNG_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`ITEM_TY`	VARCHAR(100)	NOT NULL	COMMENT '품목 구분 코드 참조',
	`RSC_ID`	VARCHAR(100)	NULL	COMMENT '품목 유형에 따라 제한 FK',
	`PRDT_ID`	VARCHAR(100)	NULL	COMMENT '품목 유형에 따라 제한 FK',
	`PRDT_OPT_ID`	VARCHAR(100)	NULL	COMMENT '품목 유형에 따라 제한 FK',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE MENU (
	`MENU_ID`	VARCHAR(100)	NOT NULL,
	`MUNU_NM`	VARCHAR(100)	NOT NULL	COMMENT '공통코드 참조',
	`MENU_ORD`	INT	NOT NULL,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE WRHOUS_LOCA (
	`ZONE_ID`	VARCHAR(100)	NOT NULL	COMMENT '식별자로 사용 복합키',
	`WRHOUS_ID`	VARCHAR(100)	NOT NULL	COMMENT '창고 식별자',
	`ITEM_TY`	VARCHAR(100)	NULL	COMMENT '공통코드 참조(자재, 완제품, 반제품)',
	`ZONE_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)자재 창고 로케이션_1',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT 'ex)활성/비활성',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE END_PROD_QC_INSP (
	`END_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NOT NULL,
	`PRCS_CTRL_ID`	VARCHAR(100)	NOT NULL,
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`INFER_QY`	INT	NOT NULL	DEFAULT 0,
	`PASS_QY`	INT	NOT NULL	DEFAULT 0,
	`INSP_QY`	INT	NOT NULL,
	`INSP_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE BOM (
	`BOM_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품 테이블 FK',
	`BOM_VER`	VARCHAR(100)	NOT NULL	COMMENT 'ex)v1',
	`VALID_FR_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`VALID_TO_DT`	DATE	NULL	COMMENT 'ex)2025-09-09',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT 'ex)사용/미사용',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE RSC_QLTY_INSP (
	`RSC_QLTY_INSP_ID`	VARCHAR(100)	NOT NULL,
	`RSC_ORDR_DETA_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`RTNGUD_QY`	FLOAT(15,5)	NOT NULL	DEFAULT 0,
	`PASS_QY`	FLOAT(15,5)	NOT NULL	DEFAULT 0,
	`INSP_QY`	FLOAT(15,5)	NOT NULL,
	`INSP_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE PROD_PLAN_DETA (
	`PROD_PLAN_DETA_ID`	VARHCAR(100)	NOT NULL,
	`PROD_PLAN_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_OPT_ID`	VARCHAR(100)	NOT NULL,
	`PLAN_QY`	INT	NOT NULL,
	`PRIORT`	INT	NOT NULL,
	`RM`	VARCHAR(100)	NULL
);

CREATE TABLE PRDT_OPT (
	`PRDT_OPT_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품과 규격에 따라 ID를 구분한다.',
	`OPT_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)홀로그램 스티커 레드',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT 'ex)활성/비활성',
	`RM`	VARCHAR(1000)	NULL	COMMENT '옵션의 특이 사항'
);

CREATE TABLE WRHOUS_WRHSDLVR (
	`WRHOUS_WRHSDLVR_ID`	VARCHAR(100)	NOT NULL,
	`RSC_RTUN_TRGET_ID`	VARCHAR(100)	NULL,
	`SEMI_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`RSC_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`END_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`DELI_DOC_REG_DETA_ID`	VARCHAR(100)	NOT NULL,
	`RSC_ID`	VARCHAR(100)	NULL	COMMENT '자재 테이블 FK',
	`PRDT_ID`	VARCHAR(100)	NULL	COMMENT '제품 테이블 FK',
	`PRDT_OPT_ID`	VARCHAR(100)	NULL	COMMENT '옵션 테이블 FK',
	`WRHOUS_ID`	VARCHAR(100)	NOT NULL	COMMENT '창고 테이블 FK',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`ZONE_ID`	VARCHAR(100)	NOT NULL	COMMENT '로케이션 테이블 FK',
	`LOT_NO`	VARCHAR(100)	NOT NULL,
	`RCVPAY_TY`	VARCHAR(100)	NOT NULL,
	`SPEC`	VARCHAR(100)	NULL	COMMENT '정확하게 기록하기 위해',
	`UNIT`	VARCHAR(100)	NULL	COMMENT '정확하게 기록하기 위해',
	`RCVPAY_QY`	FLOAT(15,5)	NOT NULL,
	`RCVPAY_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE RSC_ORDR (
	`RSC_ORDR_ID`	VARCHAR(100)	NOT NULL,
	`CO_ID`	VARCHAR(100)	NOT NULL	COMMENT '업체 테이블 FK',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK (담당자))',
	`REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE PRDT_DELI_DOC (
	`PRDT_DELI_DOC_ID`	VARCHAR(100)	NOT NULL,
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK',
	`DELI_REG_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE ROUTING (
	`PRCS_ROUTING_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT '제품 테이블 FK',
	`OPT_ID`	VARCHAR(100)	NOT NULL	COMMENT '옵션 테이블 FK'
);

CREATE TABLE CO (
	`CO_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`CO_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)예담주식회사',
	`CO_TY_ID`	VARCHAR(100)	NOT NULL	COMMENT '부코드 ID 입력',
	`RPSTR_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)김예담',
	`RPSTR_TEL`	VARCHAR(100)	NOT NULL	COMMENT 'ex)02-1234-5678',
	`BIZR_REG_NO`	VARCHAR(100)	NOT NULL	COMMENT 'ex)810-40-04516',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT '부코드 상태 구분 코드',
	`RM`	VARCHAR(1000)	NULL	COMMENT 'ex)긴급건'
);

CREATE TABLE PRCS_PROG_PRECON (
	`PRCS_PROG_PRECON_ID`	VARCHAR(100)	NOT NULL,
	`PROD_DRCT_DETA_ID`	VARCHAR(100)	NOT NULL	COMMENT '생산지시ID FK',
	`PRCS_ORD`	INT	NOT NULL	COMMENT '라우팅ID FK',
	`PRCS_ID`	VARCHAR(100)	NOT NULL	COMMENT '공정ID FK',
	`PRCS_NM`	VARCHAR(100)	NOT NULL	COMMENT '공정 테이블 참조니까 거기서 가져오면 될듯',
	`DRCT_QY`	INT	NOT NULL	COMMENT '생산지시ID FK',
	`INPT_QY`	INT	NOT NULL,
	`PROD_QY`	INT	NULL,
	`INFER_QY`	INT	NOT NULL	DEFAULT 0,
	`PASS_QY`	INT	NOT NULL	DEFAULT 0,
	`CLS_YN`	VARCHAR(100)	NOT NULL	COMMENT '공통코드 진행 전 중 완료',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE PROC_CTRL (
	`PRCS_CTRL_ID`	VARCHAR(100)	NOT NULL,
	`PRCS_PROG_PRECON_ID`	VARCHAR(100)	NOT NULL,
	`PRDT_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`PRCS_ROUTING_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`PRCS_ORD`	VARCHAR(100)	NOT NULL,
	`PRCS_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`MOLD_ID`	VARCHAR(100)	NULL	COMMENT 'FK',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`INPT_QY`	INT	NULL	COMMENT '생산량 = 투입수량(투입수량은 증가함) => 같으면 종료',
	`PROD_QY`	INT	NULL,
	`INFER_QY`	INT	NOT NULL	DEFAULT 0,
	`PASS_QY`	INT	NOT NULL	DEFAULT 0,
	`WK_FR_DTTM`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '버튼으로만 작동되게 시작 버튼',
	`WK_TO_DTTM`	DATE	NULL	COMMENT '버튼으로만 작동되게 종료 버튼',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE ROUTING_DETA (
	`PRCS_ROUTING_DETA`	VARCHAR(255)	NOT NULL,
	`PRCS_ROUTING_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`PRCS_ORD`	INT	NOT NULL	COMMENT 'ex)1',
	`PRCS_ID`	VARCHAR(100)	NOT NULL	COMMENT '공정 테이블 FK',
	`LEAD_TM`	VARCHAR(100)	NULL	COMMENT 'ex)18시간'
);

CREATE TABLE SEMI_PRDT_QLTY_INSP (
	`SEMI_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NOT NULL,
	`PRCS_CTRL_ID`	VARCHAR(100)	NOT NULL,
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT '사원 테이블 FK(담당자)',
	`INFER_QY`	INT	NOT NULL	DEFAULT 0,
	`PASS_QY`	INT	NOT NULL	DEFAULT 0,
	`INSP_QY`	INT	NOT NULL	DEFAULT 0,
	`INSP_DT`	DATE	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE SUB_CODE (
	`SUB_CODE_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`MA_CODE_ID`	VARCHAR(100)	NOT NULL,
	`SUB_CODE_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)생산 계획 관리'
);

CREATE TABLE PRCS (
	`PRCS_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`EQM_GRP_ID`	VARCHAR(100)	NOT NULL	COMMENT '설비 그룹 테이블 FK',
	`PRCS_NM`	VARCHAR(100)	NOT NULL	COMMENT 'ex)프레스 성형',
	`MOLD_USE_AT`	VARCHAR(100)	NOT NULL	COMMENT 'ex) 사용/미사용 부코드',
	`ST`	VARCHAR(100)	NOT NULL	COMMENT 'ex)활성/비활성',
	`RM`	VARCHAR(1000)	NULL
);

CREATE TABLE RSC_ORDR_DETA (
	`RSC_ORDR_DETA_ID`	VARCHAR(100)	NOT NULL	COMMENT '특정규칙 + 시퀀스',
	`RSC_ORDR_ID`	VARCHAR(100)	NOT NULL,
	`RSC_ID`	VARCHAR(100)	NOT NULL	COMMENT '자재 테이블 FK',
	`QY`	FLOAT(15,5)	NOT NULL	COMMENT '규격, 단위는 자재 테이블에 있어서 제외',
	`RM`	VARCHAR(1000)	NULL
);

ALTER TABLE PROD_DRCT ADD CONSTRAINT PK_PROD_DRCT PRIMARY KEY (
	`PROD_DRCT_ID`
);

ALTER TABLE PROD_PLAN ADD CONSTRAINT PK_PROD_PLAN PRIMARY KEY (
	`PROD_PLAN_ID`
);

ALTER TABLE DELI_REG_DETA ADD CONSTRAINT PK_DELI_REG_DETA PRIMARY KEY (
	`DELI_DOC_REG_DETA_ID`
);

ALTER TABLE WRHOUS ADD CONSTRAINT PK_WRHOUS PRIMARY KEY (
	`WRHOUS_ID`
);

ALTER TABLE MENU_PERM ADD CONSTRAINT PK_MENU_PERM PRIMARY KEY (
	`MENU_PERM_ID`
);

ALTER TABLE ACCT ADD CONSTRAINT PK_ACCT PRIMARY KEY (
	`ACCT_ID`
);

ALTER TABLE PROD_DRCT_DETA ADD CONSTRAINT PK_PROD_DRCT_DETA PRIMARY KEY (
	`PROD_DRCT_DETA_ID`
);

ALTER TABLE LOT_STC_PRECON ADD CONSTRAINT PK_LOT_STC_PRECON PRIMARY KEY (
	`LOT_INVNTRY_PRECON_ID`
);

ALTER TABLE EQM_GRP ADD CONSTRAINT PK_EQM_GRP PRIMARY KEY (
	`EQM_GRP_ID`
);

ALTER TABLE RSC ADD CONSTRAINT PK_RSC PRIMARY KEY (
	`RSC_ID`
);

ALTER TABLE MOLD ADD CONSTRAINT PK_MOLD PRIMARY KEY (
	`MOLD_ID`
);

ALTER TABLE PRDT ADD CONSTRAINT PK_PRDT PRIMARY KEY (
	`PRDT_ID`
);

ALTER TABLE RCVORD_DETA ADD CONSTRAINT PK_RCVORD_DETA PRIMARY KEY (
	`PRDT_RCVORD_DETA_ID`
);

ALTER TABLE MA_CODE ADD CONSTRAINT PK_MA_CODE PRIMARY KEY (
	`MA_CODE_ID`
);

ALTER TABLE BOM_DETA ADD CONSTRAINT PK_BOM_DETA PRIMARY KEY (
	`BOM_COMP_ID`
);

ALTER TABLE EQM ADD CONSTRAINT PK_EQM PRIMARY KEY (
	`EQM_ID`
);

ALTER TABLE QLTY_ITEM ADD CONSTRAINT PK_QLTY_ITEM PRIMARY KEY (
	`QLTY_ITEM_MNG_ID`
);

ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (
	`EMP_ID`
);

ALTER TABLE RCVORD ADD CONSTRAINT PK_RCVORD PRIMARY KEY (
	`RCVODR_ID`
);

ALTER TABLE RWMATR_RTUN_TRGET ADD CONSTRAINT PK_RWMATR_RTUN_TRGET PRIMARY KEY (
	`RSC_RTUN_TRGET_ID`
);

ALTER TABLE ITEM_QLTY_DETA ADD CONSTRAINT PK_ITEM_QLTY_DETA PRIMARY KEY (
	`ITEM_QLTY_DETA_ID`
);

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (
	`MENU_ID`
);

ALTER TABLE WRHOUS_LOCA ADD CONSTRAINT PK_WRHOUS_LOCA PRIMARY KEY (
	`ZONE_ID`
);

ALTER TABLE END_PROD_QC_INSP ADD CONSTRAINT PK_END_PROD_QC_INSP PRIMARY KEY (
	`END_PRDT_QLTY_INSP_ID`
);

ALTER TABLE BOM ADD CONSTRAINT PK_BOM PRIMARY KEY (
	`BOM_ID`
);

ALTER TABLE RSC_QLTY_INSP ADD CONSTRAINT PK_RSC_QLTY_INSP PRIMARY KEY (
	`RSC_QLTY_INSP_ID`
);

ALTER TABLE PROD_PLAN_DETA ADD CONSTRAINT PK_PROD_PLAN_DETA PRIMARY KEY (
	`PROD_PLAN_DETA_ID`
);

ALTER TABLE PRDT_OPT ADD CONSTRAINT PK_PRDT_OPT PRIMARY KEY (
	`PRDT_OPT_ID`,
	`PRDT_ID`
);

ALTER TABLE WRHOUS_WRHSDLVR ADD CONSTRAINT PK_WRHOUS_WRHSDLVR PRIMARY KEY (
	`WRHOUS_WRHSDLVR_ID`
);

ALTER TABLE RSC_ORDR ADD CONSTRAINT PK_RSC_ORDR PRIMARY KEY (
	`RSC_ORDR_ID`
);

ALTER TABLE PRDT_DELI_DOC ADD CONSTRAINT PK_PRDT_DELI_DOC PRIMARY KEY (
	`PRDT_DELI_DOC_ID`
);

ALTER TABLE ROUTING ADD CONSTRAINT PK_ROUTING PRIMARY KEY (
	`PRCS_ROUTING_ID`
);

ALTER TABLE CO ADD CONSTRAINT PK_CO PRIMARY KEY (
	`CO_ID`
);

ALTER TABLE PRCS_PROG_PRECON ADD CONSTRAINT PK_PRCS_PROG_PRECON PRIMARY KEY (
	`PRCS_PROG_PRECON_ID`
);

ALTER TABLE PROC_CTRL ADD CONSTRAINT PK_PROC_CTRL PRIMARY KEY (
	`PRCS_CTRL_ID`
);

ALTER TABLE ROUTING_DETA ADD CONSTRAINT PK_ROUTING_DETA PRIMARY KEY (
	`PRCS_ROUTING_DETA`
);

ALTER TABLE SEMI_PRDT_QLTY_INSP ADD CONSTRAINT PK_SEMI_PRDT_QLTY_INSP PRIMARY KEY (
	`SEMI_PRDT_QLTY_INSP_ID`
);

ALTER TABLE SUB_CODE ADD CONSTRAINT PK_SUB_CODE PRIMARY KEY (
	`SUB_CODE_ID`
);

ALTER TABLE PRCS ADD CONSTRAINT PK_PRCS PRIMARY KEY (
	`PRCS_ID`
);

ALTER TABLE RSC_ORDR_DETA ADD CONSTRAINT PK_RSC_ORDR_DETA PRIMARY KEY (
	`RSC_ORDR_DETA_ID`
);

ALTER TABLE PRDT_OPT ADD CONSTRAINT FK_PRDT_TO_PRDT_OPT_1 FOREIGN KEY (
	`PRDT_ID`
)
REFERENCES PRDT (
	`PRDT_ID`
);

