ALTER TABLE `WRHOUS_WRHSDLVR_MAS` ADD CONSTRAINT `PK_WRHOUS_WRHSDLVR_MAS` PRIMARY KEY (
	`WRHSDLVR_MAS_ID`
);

CREATE TABLE `WRHOUS_WRHSDLVR` (
	`WRHOUS_WRHSDLVR_ID`	VARCHAR(100)	NOT NULL,
	`WRHSDLVR_MAS_ID`	VARCHAR(100)	NOT NULL,
	`RSC_RTUN_TRGET_ID`	VARCHAR(100)	NULL,
	`RSC_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`SEMI_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`END_PRDT_QLTY_INSP_ID`	VARCHAR(100)	NULL,
	`deli_deta_id`	VARCHAR(100)	NULL,
	`RCVPAY_QY`	DECIMAL(15,5)	NOT NULL,
	`RM`	VARCHAR(1000)	NULL
);

DESC WRHOUS_WRHSDLVR;

CREATE TABLE `WRHOUS_WRHSDLVR_MAS` (
	`WRHSDLVR_MAS_ID`	VARCHAR(100)	NOT NULL,
	`RCVPAY_TY`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`EMP_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`RSC_ID`	VARCHAR(100)	NULL	COMMENT 'FK',
	`PRDT_ID`	VARCHAR(100)	NULL	COMMENT 'FK',
	`PRDT_OPT_ID`	VARCHAR(100)	NULL	COMMENT 'FK',
	`WRHOUS_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`ZONE_ID`	VARCHAR(100)	NOT NULL	COMMENT 'FK',
	`LOT_NO`	VARCHAR(100)	NOT NULL,
	`SPEC`	VARCHAR(100)	NULL,
	`UNIT`	VARCHAR(100)	NULL,
	`ALL_RCVPAY_QY`	DECIMAL(15,5)	NOT NULL,
	`RCVPAY_DT`	VARCHAR(100)	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`RM`	VARCHAR(1000)	NULL
);

ALTER TABLE `WRHOUS_WRHSDLVR` ADD CONSTRAINT `PK_WRHOUS_WRHSDLVR` PRIMARY KEY (
	`WRHOUS_WRHSDLVR_ID`
);

select * from wrhous_wrhsdlvr;

ALTER TABLE WRHOUS_WRHSDLVR_MAS
  ADD INDEX IX_WW__RCVPAY_TY (RCVPAY_TY),
  ADD CONSTRAINT FK_WRHSDLVR_MAS_RCVPAY_TY
    FOREIGN KEY (RCVPAY_TY) REFERENCES SUB_CODE (SUB_CODE_ID);
    
    SELECT * FROM RSC_QLTY_INSP;
    DESC wrhous_wrhsdlvr;
    -- 창고 수불
ALTER TABLE WRHOUS_WRHSDLVR
  ADD CONSTRAINT FK_WRHSDLVR_MAS_ID
     FOREIGN KEY (WRHSDLVR_MAS_ID) REFERENCES WRHOUS_WRHSDLVR_MAS (WRHSDLVR_MAS_ID),
  ADD CONSTRAINT FK_RSC_RTUN_TRGET_ID
    FOREIGN KEY (RSC_RTUN_TRGET_ID) REFERENCES RSC_RTUN_TRGET (RSC_RTUN_TRGET_ID),

  ADD CONSTRAINT FK_SEMI_PRDT_QLTY_INSP_ID
    FOREIGN KEY (SEMI_PRDT_QLTY_INSP_ID)    REFERENCES SEMI_PRDT_QLTY_INSP (SEMI_PRDT_QLTY_INSP_ID),
  ADD CONSTRAINT FK_END_PRDT_QLTY_INSP_ID
    FOREIGN KEY (END_PRDT_QLTY_INSP_ID)    REFERENCES END_PRDT_QLTY_INSP (END_PRDT_QLTY_INSP_ID),
  ADD CONSTRAINT FK_deli_deta_id
    FOREIGN KEY (deli_deta_id)   REFERENCES deli_deta (deli_deta_id)
;
ALTER TABLE WRHOUS_WRHSDLVR_MAS
  ADD CONSTRAINT FK_LOT_INVNTRY_PRECON_ID
    FOREIGN KEY (LOT_INVNTRY_PRECON_ID)   REFERENCES lot_stc_precon (LOT_INVNTRY_PRECON_ID);
    
    DESC wrhous_wrhsdlvr_mas;

ALTER TABLE WRHOUS_WRHSDLVR_MAS
ADD COLUMN LOT_INVNTRY_PRECON_ID VARCHAR(100);

SELECT * FROM lot_stc_precon;

INSERT INTO WRHOUS_WRHSDLVR
(WRHOUS_WRHSDLVR_ID, WRHSDLVR_MAS_ID, RSC_RTUN_TRGET_ID, RSC_QLTY_INSP_ID, SEMI_PRDT_QLTY_INSP_ID, END_PRDT_QLTY_INSP_ID, DELI_DETA_ID, RCVPAY_QY, RM) VALUES
('WWD001', 'WWM001', 'RTN001', 'RSC001', NULL,    NULL,    'DEL001',  10.00000, '더미 비고 1'),
('WWD002', 'WWM002', 'RTN002', NULL,     'SEMI01', NULL,    'DEL002',  20.00000, '더미 비고 2'),
('WWD003', 'WWM003', 'RTN003', NULL,     NULL,     'END001','DEL003',  30.50000, '더미 비고 3'),
('WWD004', 'WWM004', 'RTN004', 'RSC002', NULL,     NULL,    'DEL004',   5.25000, '더미 비고 4'),
('WWD005', 'WWM005', 'RTN005', NULL,     NULL,     'END002','DEL005', 100.00000, '더미 비고 5');

INSERT INTO WRHOUS_WRHSDLVR_MAS
(WRHSDLVR_MAS_ID, RCVPAY_TY, EMP_ID, RSC_ID, PRDT_ID, PRDT_OPT_ID, WRHOUS_ID, ZONE_ID, LOT_NO, SPEC, UNIT, ALL_RCVPAY_QY, RCVPAY_DT, LOT_INVNTRY_PRECON_ID) VALUES
('WWM001', 'IN',  'EMP001', 'RSC001', 'PRD001', 'PRD001', 'WRH001', 'WRH001', 'LOT-A1', '20g', 'EA',  10.00000, '2025-10-16', 'LOT001'),
('WWM002', 'IN',  'EMP002', 'RSC002', 'PRD002', 'PRD002', 'WRH002', 'WRH002', 'LOT-B1', '30g', 'EA',  50.00000, '2025-10-16', 'LOT002'),
('WWM003', 'OUT', 'EMP003', 'RSC003', 'PRD003', 'PRD003', 'WRH003', 'WRH003', 'LOT-C1', '20g', 'EA',  15.25000, '2025-10-16', 'LOT003'),
('WWM004', 'IN',  'EMP004', 'RSC004', 'PRD004', 'PRD004', 'WRH004', 'WRH004', 'LOT-D1', '40g', 'EA', 200.00000, '2025-10-16', 'LOT004'),
('WWM005', 'OUT', 'EMP005', 'RSC005', 'PRD005', 'PRD005', 'WRH005', 'WRH005', 'LOT-E1', '50g', 'EA',   5.00000, '2025-10-16', 'LOT005');